services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: placement_db
      POSTGRES_USER: placement_user
      POSTGRES_PASSWORD: placement_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U placement_user -d placement_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - placement_net

  app:
    build: .
    container_name: campusplacementportal-app-cd
    image: campus-placement-portal:v2
    ports:
      - "8083:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/placement_db?options=-c+TimeZone%3DUTC
      DB_USERNAME: placement_user
      DB_PASSWORD: placement_password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - placement_net

networks:
  placement_net:

volumes:
  postgres_data:

