spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/placement_db}
spring.datasource.username=${DB_USER:placement_user}
spring.datasource.password=${DB_PASSWORD:placement_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
spring.thymeleaf.cache=false
spring.mvc.hiddenmethod.filter.enabled=true
